# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0003_auto_20190722_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='user',
            new_name='created_by',
        ),
    ]
