# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_app', '0004_auto_20190722_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.CharField(max_length=10),
        ),
    ]
